### ISSUE TITLE
Clear up unneeded dev dependencies

### ISSUE THREAD

**Issue by Ryan-Reddy** [domits1/Domits#1698]
**Is there an existing issue for this?**
- [x] no

![Image](https://github.com/user-attachments/assets/c31c44c9-f4ac-4671-a72f-4b613db5c86b)

- [ ] 1. Install depcheck:
First, you need to install depcheck. You can install it globally or as a devDependency.

To install it globally:

bash
Copy
Edit
npm install -g depcheck
Or as a devDependency:

bash
Copy
Edit
npm install --save-dev depcheck

- [ ] 2. Run depcheck:Once depcheck is installed, run it in the root of your project (where your package.json file is located).

Run the following command in your terminal:

bash
Copy
Edit
depcheck
This will analyze your project and output a list of:

Unused dependencies: Dependencies that are listed in your package.json but aren't used in the code.
Missing dependencies: Dependencies that are used in your code but are not listed in package.json.
Unused devDependencies: Dev dependencies that are not being used in the project.

- [ ] 3. Interpreting the Output:
After running the command, you'll see output like this:

bash
Copy
Edit
Unused dependencies
* some-unused-package

Missing dependencies
* some-missing-package

- [ ] 4. Install depcheck in your workflow
something like this:
```yml
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify the Node.js version here

    - name: Install dependencies
      run: |
        npm install

    - name: Run depcheck
      run: |
        npx depcheck
```
