### ISSUE TITLE
Ci pipeline debugging:

### ISSUE THREAD

**Issue by giannivanlooij** [domits1/Domits#268]
Expected situation: I expected:

the pipeline to run the cypress task, which means installing all the packages and running the test scripts

Actual situation: What seems to happen is

```
> domits@1.0.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './aws-exports' in '/home/runner/work/Domits/Domits/web/src'


Error: The process '/usr/local/bin/npm' failed with exit code 1

```

the pipeline builds a environment/build/artifact that is used as a test environment for running the script. the problem is that the amazon export file is not available within this environment

i tried to implement it at first which does not work. then the question struck: "why does the pipeline need access to the amazon backhand at all?""

What I researched so far:

does initialising a aws environment work?
how to pass the amazon credentials in the ci.yml file?
does cypress run when the scripts are turned off?
does the mostpros file work with this pipeline?
is vite needed perhaps?

Possibilities I see:

making the pipeline work by identifying the part of the build that requires the export file and turn if off.
identifying the part that does not make the aws export file and fixing the problem there

Please advise.

**Comment by giannivanlooij** [comment]
I Figured it out finally!

the original code:

name: Cypress Tests

on:
  push:
    branches:
      - 'acceptance'

```
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly

      - name: Install dependencies
        run: |
          cd web
          npm ci --verbose

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          runTests: false

      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          build: npm run build
          start: npx vite --host
```

the new code: 

```
name: Cypress Tests

on:
  push:
    branches:
      - 'acceptance'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: |
          cd web
          npm ci --verbose

      # Run your Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          start: npx vite --host
```
I don't know why the cypress install was triggering the aws export. but while installing packages cypress was included there as well. which means that the cypress install was unnecessary
